# Generated by Django 6.0.4 on 2026-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='dark', max_length=10),
        ),
    ]
